backend:
  name: git-gateway
  branch: main
media_folder: "dist/assets/event"
public_folder: "/assets/event"
collections:
  - name: "event"
    label: "Event"
    folder: "src/event"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Highlight", name: "highlight", widget: "markdown"}
      - { label: "Tags", name: "tags", widget: "list" , default: ["event"] }
      - { label: "Featured image", name: "image", widget: "image" }
      - { label: "Image caption", name: "caption", widget: "string" }
